# version: '3.8'

# Dev mode only!!!

services:

  esilo-api:
    container_name: esilo-api
    hostname: esilo-api
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
      # dockerfile: ./Dockerfile
      args:
        - ESILO_PORT=9096
    command: uvicorn server:app --host 0.0.0.0 --port 9096 --reload
    image: omarzos/esilo-api
    ports:
      - 9096:9096
    environment:
      - ESILO_PORT=9096
      - SQL_SCHEMA=${SQL_SCHEMA}
      - SQL_HOST=${SQL_HOST}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=${SQL_PORT}
    networks:
      - gluttex-net
    volumes:
      - ./:/code
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  volumes:
    driver: local


networks:
  gluttex-net:
    external: true
#     driver: bridge