# version: '3.8'

# Dev mode only!!!

services:

  emagrad-fs:
    container_name: emagrad-fs
    hostname: emagrad-fs
    restart: unless-stopped
    build:
      context: ./
      # dockerfile: ./Dockerfile.dev
      dockerfile: ./Dockerfile
      args:
        - FS_PORT=9099
    # command: uvicorn server:app --host 0.0.0.0 --port 9099 --reload
    image: omarzos/emagrad-fs
    ports:
      - 9099:9099
    environment:
      - FS_PORT=9099
      - FS_BASE_STORAGE=${FS_BASE_STORAGE}
      - FS_CACHE_STORAGE=${FS_CACHE_STORAGE}
    # networks:
    #   - gluttex-net
    volumes:
      - ./:/code
      - ./volumes/fs/:/fs/
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


volumes:
  volumes:
    driver: local


# networks:
#   gluttex-net:
#     name: gluttex-net
#     driver: bridge